apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q41y6122k-python
  janus-idp.io/tekton: q41y6122k-python
  backstage.io/kubernetes-id: q41y6122k-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q41y6122k-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
